import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { keyOf } from './corpus/lib.mjs';

// Quality gate: the legacy DB is full of acronyms, initials and value-annotated
// junk ("DCC [700]", "ACM", "A.D.L", "Bo"). Strip the bracket annotations and
// drop the clear noise. Returns the cleaned phrase, or null to drop it.
// db-source.txt on disk is untouched — only the served DB is filtered.
function clean(p) {
  p = p.replace(/\s*\[[^\]]*\]\s*$/, '').trim();   // trailing "[700]" value tags
  if (!p) return null;
  if (/[.]/.test(p)) return null;                  // initials / abbreviations (A.D.L, O.B.)
  const alpha = p.replace(/[^a-zA-Z]/g, '');
  if (alpha.length < 3) return null;               // 2-letter junk (Bo, El, MD, Q)
  if (alpha.length >= 2 && alpha === alpha.toUpperCase()) return null; // all-caps acronyms (ACM, FBI, EEG)
  // every 2+ letter word needs a consonant (kills all-vowel fragments: Aao, AoA, Eae)
  for (const w of p.split(/\s+/)) { const a = w.replace(/[^a-z]/gi, ''); if (a.length >= 2 && !/[bcdfghjklmnpqrstvwxz]/i.test(a)) return null; }
  return p;
}

// Merge the hand-curated phrases with the ingested public-domain corpus,
// dedup on the normalized key (diacritic/punct/whitespace-insensitive — a
// superset of the legacy lowercase-exact dedup), and emit the runtime DB.
// db-source.txt (curated) first, then db-corpus.txt (latest ingest). The index
// where the corpus begins lets Wisdom Mode prioritize the ingested material.
const FILES = ['db-source.txt', 'db-corpus.txt'].filter(existsSync);
const seen = new Set();
const out = [];
let corpusStart = Infinity;
for (const file of FILES) {
  if (file === 'db-corpus.txt') corpusStart = out.length; // boundary after curated phrases
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const raw = line.trim();
    if (!raw || raw === 'CREATE_GEMATRO_DB') continue;
    const phrase = clean(raw);
    if (!phrase) continue;
    const key = keyOf(phrase);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(phrase);
  }
}
if (corpusStart === Infinity) corpusStart = out.length; // no corpus file present
mkdirSync('public', { recursive: true });
// Ship gzipped: the plain text is ~31 MB which exceeds Cloudflare Pages' 25 MiB
// per-file limit. The worker fetches this and inflates it with DecompressionStream
// (native). Also ~3× smaller transfer. We deliberately do NOT write the plain .txt
// into public/ so an oversized file can never get deployed.
const gz = gzipSync(out.join('\n') + '\n', { level: 9 });
writeFileSync('public/cyphers-db.txt.gz', gz);
const version = createHash('sha1').update(gz).digest('hex').slice(0, 10); // cache-bust the worker fetch
// generated meta so the UI never shows a stale total and Wisdom Mode knows the split
writeFileSync('src/data/db-meta.ts',
  `// generated by scripts/build-db.mjs — do not edit\n` +
  `export const PHRASE_COUNT = ${out.length};\n` +
  `export const CORPUS_START = ${corpusStart}; // indices >= this are from the latest ingest\n` +
  `export const DB_VERSION = '${version}';\n`);
console.log(`Wrote ${out.length} phrases (corpus @ ${corpusStart}, v${version}) → public/cyphers-db.txt.gz (${(gz.length / 1048576).toFixed(1)} MB)`);
