import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const src = readFileSync('legacy/calc/ciphers.js', 'utf8');
const captured = [];
// Legacy signature: (name, category, H,S,L, cArr, vArr, diacriticsAsRegular=true, enabled=false, caseSensitive=false)
function cipher(name, category, H, S, L, cArr, vArr, dia = true, enabled = false, cs = false) {
  captured.push({ name, category, hsl: [H, S, L], cArr, vArr, diacriticsAsRegular: dia, enabled, caseSensitive: cs });
  return captured[captured.length - 1];
}
let cipherList = [];
// Indirect eval `(0, eval)(src)` runs in GLOBAL scope per spec, which cannot see this module's
// local `function cipher` / `let cipherList` (ESM module scope is not the global scope). Expose
// the stub + a global cipherList binding on globalThis so the legacy file's bare
// `cipherList = [ new cipher(...), ... ]` assignment resolves against them, then read back.
globalThis.cipher = cipher;
globalThis.cipherList = cipherList;
// eslint-disable-next-line no-eval
(0, eval)(src);
cipherList = globalThis.cipherList;

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const seen = new Set();
const list = (cipherList.length ? cipherList : captured).map((c) => {
  let id = slug(`${c.category}-${c.name}`);
  while (seen.has(id)) id += '-x';
  seen.add(id);
  return { id, name: c.name, category: c.category, hsl: c.hsl, cArr: c.cArr, vArr: c.vArr,
           diacriticsAsRegular: c.diacriticsAsRegular, enabled: c.enabled, caseSensitive: c.caseSensitive };
});

mkdirSync('src/data', { recursive: true });
const out = `// AUTO-GENERATED by scripts/extract-ciphers.mjs — do not edit by hand.\n`
  + `import type { Cipher } from '../engine/types';\n`
  + `export const ciphers: Cipher[] = ${JSON.stringify(list, null, 2)};\n`;
writeFileSync('src/data/ciphers.ts', out);
console.log(`Wrote ${list.length} ciphers to src/data/ciphers.ts`);
