// generated by scripts/build-db.mjs — do not edit
export const PHRASE_COUNT = 1243170;
export const CORPUS_START = 221026; // indices >= this are from the latest ingest
export const DB_VERSION = '58ae6fd0d9';
